config/routes.rb
NIRCA::Application.routes.draw do
  root :to => 'races#index'
  
  devise_for :users

  resources :teams do
    resources :runners
  end

  resources :event_entries
  
  resources :races do
    resources :events
  end
  
  match 'not_authorized' => 'races#index', :as => :login_redirect
  
  match 'teams/join/:id' => 'teams#join', :as => :jointeam
  
  match 'events/new_event_entry' => 'events#new_event_entry', :as => :enter_event
  
  match 'events/overview/:id' => 'events#view_event_overview', :as => :event_overview
  

end

app/models/race.rb
class Race < ActiveRecord::Base
  has_many :events
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  # GET /races
  # GET /races.json
  before_filter :authenticate_user!, :except => [:index, :show]
  
  def index
    @races = Race.all
    @teams = Team.all
    @team_names = {}
    @teams.each do |team|
      @team_names[team.id] = team.school_name
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @races }
    end
  end

  # GET /races/1
  # GET /races/1.json
  def show
    @race = Race.find(params[:id])
    @events = @race.events
    @teams = Team.all
    @team_names = {}
    @teams.each do |team|
      @team_names[team.id] = team.school_name
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @race }
    end
  end

  # GET /races/new
  # GET /races/new.json
  def new
    @race = Race.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @race }
    end
  end

  # GET /races/1/edit
  def edit
    @race = Race.find(params[:id])
  end

  # POST /races
  # POST /races.json
  def create
    @race = Race.new(params[:race])
    @race.team_id = params[:team_id]
    respond_to do |format|
      if @race.save
        format.html { redirect_to @race, :notice => 'Race was successfully created.' }
        format.json { render :json => @race, :status => :created, :location => @race }
      else
        format.html { render :action => "new" }
        format.json { render :json => @race.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /races/1
  # PUT /races/1.json
  def update
    @race = Race.find(params[:id])

    respond_to do |format|
      if @race.update_attributes(params[:race])
        format.html { redirect_to @race, :notice => 'Race was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @race.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  
  

  # DELETE /races/1
  # DELETE /races/1.json
  def destroy
    @race = Race.find(params[:id])
    @race.destroy

    respond_to do |format|
      format.html { redirect_to races_url }
      format.json { head :ok }
    end
  end
end

app/helpers/races_helper.rb
module RacesHelper
end

app/views/races/_form.html.erb
<%= form_for(@race) do |f| %>
  <% if @race.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@race.errors.count, "error") %> prohibited this race from being saved:</h2>

      <ul>
      <% @race.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%f.hidden_field :team_id, :value => session[:team]%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/races/edit.html.erb
<h1>Editing race</h1>

<%= render 'form' %>

<%= link_to 'Show', @race %> |
<%= link_to 'Back', races_path %>

app/views/races/index.html.erb
<h1>NIRCA Spring 2012 Track Races</h1>



<% @races.each do |race| %>
<div class="race_info">
	<h3><%= race.name%><br />
	<%= race.location %><br />
	<%= @team_names[race.team_id]%>
	</h3>
	<span class="edition">
		<%= link_to 'View Details', race %> 
		<% if race.team_id == session[:team]%>
		
		| <%= link_to 'Edit', edit_race_path(race) %> | <%= link_to 'Destroy', race, :confirm => 'Are you sure?', :method => :delete %>
		<%end%>
</div>


 
<% end %>

<br />

<%= link_to 'New Race', new_race_path %>

app/views/races/new.html.erb
<h1>New race</h1>

<%= render 'form' %>

<%= link_to 'Back', races_path %>

app/views/races/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @race.name %>
</p>

<p>
  <b>Location:</b>
  <%= @race.location %>
</p>

<p>
  <b>Team:</b>
  <%= @team_names[@race.team_id] %>
</p>
<div id="events">
	<h3>Events!</h3>
	<table>
		<% if @race.events.count > 0 %>
	<% @race.events.each do |event|%>
	<tr>
	<td><%= event.name%></td>
	<td><%= event.distance.to_s + event.units%></td>
	<td><%= link_to "Enter For this Event", :controller => "event_entries", :action => "new", :event_id => event.id %></td></tr>
	<% end %>	
<% end %>
<% if @race.team_id == session[:team] %>
	<%= link_to "Add Event", new_race_event_path(@race, @event) %>
	<%end%>
</div>
	
	



<%= link_to 'Edit', edit_race_path(@race) %> |
<%= link_to 'Back', races_path %>