config/routes.rb
NIRCA::Application.routes.draw do
  root :to => 'races#index'
  
  devise_for :users

  resources :teams do
    resources :runners
  end

  resources :event_entries
  
  resources :races do
    resources :events
  end
  
  match 'not_authorized' => 'races#index', :as => :login_redirect
  
  match 'teams/join/:id' => 'teams#join', :as => :jointeam
  
  match 'events/new_event_entry' => 'events#new_event_entry', :as => :enter_event
  
  match 'events/overview/:id' => 'events#view_event_overview', :as => :event_overview
  

end

app/models/runner.rb
class Runner < ActiveRecord::Base
  belongs_to :team
  belongs_to :user
  
  
  attr_accessible :first_name, :last_name
  validates_presence_of :first_name, :last_name
  
end

app/controllers/runners_controller.rb
class RunnersController < ApplicationController
  # GET /runners
  # GET /runners.json
  before_filter :authenticate_user!, :only => [:create]
  
  
 
  
  def index
    @runners = Runner.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @runners }
    end
  end

  # GET /runners/1
  # GET /runners/1.json
  def show
    @runner = Runner.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @runner }
    end
  end

  # GET /runners/new
  # GET /runners/new.json
  def new
    @runner = Runner.new
    @team = Team.find(params[:team_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @runner }
    end
  end

  # GET /runners/1/edit
  def edit
    @runner = Runner.find(params[:id])
    @team = Team.find(@runner.team_id)
  end

  # POST /runners
  # POST /runners.json
  def create
    @team = Team.find(params[:team_id])
    @runner = @team.runners.build(params[:runner])
    @runner.team_id = session[:team]

    respond_to do |format|
      if @runner.save
        format.html { redirect_to @team, :notice => 'Runner was successfully created.' }
        format.json { render :json => @team, :status => :created, :location => @team}
      else
        format.html { render :action => "new" }
        format.json { render :json => @runner.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /runners/1
  # PUT /runners/1.json
  def update
    @runner = Runner.find(params[:id])
    @team = Team.find(params[:team_id])
    respond_to do |format|
      if @runner.update_attributes(params[:runner])
        format.html { redirect_to @runner, :notice => 'Runner was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @runner.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /runners/1
  # DELETE /runners/1.json
  def destroy
    @runner = Runner.find(params[:id])
    @runner.destroy
    @team = Team.find(@runner.team_id)

    respond_to do |format|
      format.html { redirect_to @team }
      format.json { head :ok }
    end
  end
end

app/helpers/runners_helper.rb
module RunnersHelper
end

app/views/runners/_form.html.erb
<%= form_for([@team, @runner]) do |f| %>
  <% if @runner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@runner.errors.count, "error") %> prohibited this runner from being saved:</h2>

      <ul>
      <% @runner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :team_name %><br />
    <b><%= @team.school_name%></b>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
<div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/runners/edit.html.erb
<h1>Editing runner</h1>

<%= render 'form' %>

<%= link_to 'Show', team_runner_path %> |
<%= link_to 'Back', team_path, :id => @team.id %>

app/views/runners/index.html.erb
<h1>Listing runners</h1>

<table>
  <tr>
    <th>Team</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @runners.each do |runner| %>
  <tr>
    <td><%= runner.team_id %></td>
    <td><%= runner.name %></td>
    <td><%= link_to 'Show', runner %></td>
    <td><%= link_to 'Edit', edit_runner_path(runner) %></td>
    <td><%= link_to 'Destroy', runner, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Runner', new_runner_path %>

app/views/runners/new.html.erb
<h1>New runner</h1>

<%= render 'form' %>

<%= link_to 'Back', team_runners_path %>

app/views/runners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Team:</b>
  <%= @runner.team_id %>
</p>

<p>
  <b>Name:</b>
  <%= @runner.name %>
</p>


<%= link_to 'Edit', edit_runner_path(@runner) %> |
<%= link_to 'Back', runners_path %>