config/routes.rb
NIRCA::Application.routes.draw do
  root :to => 'races#index'
  
  devise_for :users

  resources :teams do
    resources :runners
  end

  resources :event_entries
  
  resources :races do
    resources :events
  end
  
  match 'not_authorized' => 'races#index', :as => :login_redirect
  
  match 'teams/join/:id' => 'teams#join', :as => :jointeam
  
  match 'events/new_event_entry' => 'events#new_event_entry', :as => :enter_event
  
  match 'events/overview/:id' => 'events#view_event_overview', :as => :event_overview
  

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :race
  has_many :event_entries
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new
    @race = Race.find(params[:race_id])
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @race = Race.find(params[:race_id])
    @event = @race.events.build(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @race, :notice => 'Event was successfully created.' }
        format.json { render :json => @race, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.json { render :json => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, :notice => 'Event was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @event.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def view_event_overview
    @event = Event.find(params[:id])
    
  end
  
  
  def new_event_entry
    @event = Event.find(params[:event_id])
    @entry = EventEntry.new
    @entry.runners = params[:runners]
    @entry.team_id = params[:team_id]
    @event.event_entries << @entry
    if @event.save
      redirect_to @entry, :notice => "Entry successful!"
    else
      redirect_to races_url, :notice => "There was an error."
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :ok }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for([@race, @event]) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :distance %><br />
    <%= f.text_field :distance %>
  </div>
  <div class="field">
    <%= f.label :units %><br />
    <%= f.radio_button :units, :miles %>mi
	<%= f.radio_button :units, :kilometers %>km
	<%= f.radio_button :units, :meters %>m
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing all events</h1>


<table>
  <tr>
    <th>Race</th>
    <th>Distance</th>
    <th>Units</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.race_id %></td>
    <td><%= event.distance %></td>
    <td><%= event.units %></td>
    <td><%= event.name %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/events/new.html.erb
<h1>New event for <%= @race.name%></h1>

<%= render 'form' %>

<%= link_to 'Back', race_events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Race:</b>
  <%= @event.race_id %>
</p>

<p>
  <b>Distance:</b>
  <%= @event.distance %>
</p>

<p>
  <b>Units:</b>
  <%= @event.units %>
</p>

<p>
  <b>Name:</b>
  <%= @event.name %>
</p>


<%= link_to 'Back', events_path %>

app/views/events/view_event_overview.html.erb
<h1>Entries for Event: <%= @event.name%></h1>


<% @event.event_entries.each do |entry|%>
<div class="event_entry">
	<p>
		<b>School Name:</b><%= entry.team_id%>
	</p>
	<p><b>Runners:</b><br />
		<% entry.runners.each do |runner|%>
		<%= runner%><br />
		<% end %>
	</p>
</div>
	<% end %>