config/routes.rb
NIRCA::Application.routes.draw do
  root :to => 'races#index'
  
  devise_for :users

  resources :teams do
    resources :runners
  end

  resources :event_entries
  
  resources :races do
    resources :events
  end
  
  match 'not_authorized' => 'races#index', :as => :login_redirect
  
  match 'teams/join/:id' => 'teams#join', :as => :jointeam
  
  match 'events/new_event_entry' => 'events#new_event_entry', :as => :enter_event
  
  match 'events/overview/:id' => 'events#view_event_overview', :as => :event_overview
  

end

app/models/event_entry.rb
class EventEntry < ActiveRecord::Base
  belongs_to :event
  serialize :runners, Array
end

app/controllers/event_entries_controller.rb
class EventEntriesController < ApplicationController
  # GET /event_entries
  # GET /event_entries.json
  before_filter :authenticate_user!
  
  def index
    @event_entries = EventEntry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @event_entries }
    end
  end

  # GET /event_entries/1
  # GET /event_entries/1.json
  def show
    @event_entry = EventEntry.find(params[:id])
    @runners = @event_entry.runners

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @event_entry }
    end
  end

  # GET /event_entries/new
  # GET /event_entries/new.json
  def new
    @event_entry = EventEntry.new
    @event = Event.find(params[:event_id])
    @team = Team.find(session[:team])
    @runners = @team.runners
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @event_entry }
    end
  end

  # GET /event_entries/1/edit
  def edit
    @event_entry = EventEntry.find(params[:id])
  end

  # POST /event_entries
  # POST /event_entries.json
  def create
    @event = Event.find(params[:event_id])
    @event_entry = @event.event_entries.build(params[:event_entry])

    respond_to do |format|
      if @event_entry.save
        format.html { redirect_to @event, :notice => 'Event entry was successfully created.' }
        format.json { render :json => @event, :status => :created, :location => @event_entry }
      else
        format.html { render :action => "new" }
        format.json { render :json => @event_entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /event_entries/1
  # PUT /event_entries/1.json
  def update
    @event_entry = EventEntry.find(params[:id])

    respond_to do |format|
      if @event_entry.update_attributes(params[:event_entry])
        format.html { redirect_to @event_entry, :notice => 'Event entry was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @event_entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /event_entries/1
  # DELETE /event_entries/1.json
  def destroy
    @event_entry = EventEntry.find(params[:id])
    @event_entry.destroy

    respond_to do |format|
      format.html { redirect_to event_entries_url }
      format.json { head :ok }
    end
  end
end

app/helpers/event_entries_helper.rb
module EventEntriesHelper
end

app/views/event_entries/_form.html.erb
<%= form_tag({:controller => "events", :action => "new_event_entry", :method => "POST"}) %>
  <% if @event_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event_entry.errors.count, "error") %> prohibited this event_entry from being saved:</h2>

      <ul>
      <% @event_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
   <%= @event.name%>
  </div>

  <div class="field">
	<% runner_array = @runners.map { |runner| [runner.first_name + " " +  runner.last_name, runner.first_name + " " + runner.last_name]}%>
   Select the runners competing in this event<br />
    <%= select_tag(:runners, options_for_select(runner_array), :multiple => true) %>
	<%= hidden_field_tag(:event_id, params[:event_id])%>
	<%= hidden_field_tag(:team_id, current_user.team_id)%>
  </div>

  <div class="actions">
    <%= submit_tag("Enter Runners")%>
  </div>

app/views/event_entries/edit.html.erb
<h1>Editing event_entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @event_entry %> |
<%= link_to 'Back', event_entries_path %>

app/views/event_entries/index.html.erb
<h1>Listing Entries</h1>

<table>
  <tr>
    <th>Event</th>
    <th>Runners</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @event_entries.each do |event_entry| %>
  <tr>
    <td><%= event_entry.event_id %></td>
    <td><%= event_entry.runners %></td>
    <td><%= link_to 'Show', event_entry %></td>
    <td><%= link_to 'Edit', edit_event_entry_path(event_entry) %></td>
    <td><%= link_to 'Destroy', event_entry, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event entry', new_event_entry_path %>

app/views/event_entries/new.html.erb
<h1>Enter Runners for this event</h1>

<%= render 'form' %>

app/views/event_entries/show.html.erb
<p id="notice"><%= notice %></p>

  <b>Event:</b>
  <%= @event_entry.event_id %>
</p>

<p>
	<b>School:</b>
	<%= @event_entry.team_id%>
	</p>
<p>
  <b>Runners:</b>
  <% @runners.each do |runner|	%>
<%= runner %><br />
	<% end %>

</p>


<%= link_to 'Edit', edit_event_entry_path(@event_entry) %> 